### PR TITLE
More data for the indeed job feature

### PR DESCRIPTION
**Pull request by SwetaSengupta**

### CODE REVIEW

**Review by mark-blasquino — COMMENTED** [review]
files are no longer necessary, datasets are already on a separate pull request and reformatted to match the prior datasets. im recommending that the pull request be cancelled.

**Comment by mark-blasquino** [comment]
files are no longer necessary, datasets are already on a separate pull request and reformatted to match the prior datasets. im recommending that the pull request be cancelled.

**Comment by LambdaTheda** [comment]
> _No description provided._

if u have time maybe add a brief description; eg where the data was scraped (especially if not using the same Indeed API)

**Review by LambdaTheda — COMMENTED** [review]
do we have csv for all 117 cities at this point?

**Comment by LambdaTheda** [comment]
thank you looks good!

**Comment by mark-blasquino** [comment]
> files are no longer necessary, datasets are already on a separate pull request and reformatted to match the prior datasets. im recommending that the pull request be cancelled.

can be approved, but please dont merge

**Review by LambdaTheda — APPROVED** [review]

**Review by mark-blasquino — APPROVED** [review]

**Pull request merged**
